### ISSUE TITLE
Data fields written in random order

### ISSUE THREAD

**Issue by jryans** [matrix-org/rageshake#23]
The fields from `p.Data` (such as "device_id", "Version", etc.) are sent unsorted to the details file and GH issue (presumably because we're iterating a Go map which may put them in any order).

It would be better to sort first, so that multiple reports are easier to scan.

**Comment by gernest** [comment]
@jryans how can this be reproduced? From my understanding the default behaviour is the keys are sorted lexicographically here is the docs for it https://golang.org/pkg/encoding/json/#Marshal

**Comment by turt2live** [comment]
basically this (fields blurred because real data):

![image](https://user-images.githubusercontent.com/1190097/55832311-8a36f400-5ad2-11e9-94ea-18f903a38804.png)

vs

![image](https://user-images.githubusercontent.com/1190097/55832317-8e631180-5ad2-11e9-8d7d-f8d913a041fb.png)

**Comment by gernest** [comment]
Okay, I think I found that code. Indeed iteration on map don't preserve order. Apologies I misunderstood the question.

@turt2live correct me if I'm wrong, the fields mentioned here are the one appearing in saved logs right?

**Comment by turt2live** [comment]
Yup, and in the github issue which the server posts to

**Comment by gernest** [comment]
Thanks, will have a patch in a moment.
