### ISSUE TITLE
New release and Docker build

### ISSUE THREAD

**Issue by awesome-manuel** [matrix-org/rageshake#34]
@richvdh can you issue a new release and trigger a Docker image build?

**Comment by richvdh** [comment]
I'm not aware that we publish docker images of this project. Is this a request to do so?

**Comment by awesome-manuel** [comment]
Ah right, Docker is only available for sygnal. A new release would be nice.
We have a Docker image here: https://hub.docker.com/r/awesometechnologies/rageshake

**Comment by richvdh** [comment]
https://github.com/matrix-org/rageshake/releases/tag/v1.1
