### ISSUE TITLE
Rageshake server does not accept "log.gz" as a valid file suffix", as used by element-android

### ISSUE THREAD

**Issue by michaelkaye** [matrix-org/rageshake#40]
**Describe the bug**

element-android submits rageshakes with gzipped file parts, eg:

https://github.com/vector-im/element-android/blob/develop/vector/src/main/java/im/vector/app/features/rageshake/BugReporter.kt#L700 creates gzipped files named with a .gz extension

https://github.com/vector-im/element-android/blob/develop/vector/src/main/java/im/vector/app/features/rageshake/BugReporter.kt#L299 creates Parts with the filename set to the name

Rageshake server rejects the name and overwrites with a good one as it doesn't match the regular expression here:

https://github.com/matrix-org/rageshake/blob/master/submit.go#L427

It then replaces it with a logs-0000.gz style extension.

This makes it hard to handle crash data, logcat data and log files separately.

So rather than getting the following files:
```
logcat.log.gz
logs-1.log.gz
logs-2.log.gz
logs-3.log.gz
logs-4.log.gz
logs-5.log.gz
logs-6.log.gz
logs-7.log.gz
```

We get the following files:
```
logs-0000.txt.gz (this is the logcat one)
logs-0001.txt.gz
logs-0002.txt.gz
logs-0003.txt.gz
logs-0004.txt.gz
logs-0005.txt.gz
logs-0006.txt.gz
logs-0007.txt.gz
```

Unsure whether to fix in the rageshake server (and accept *.gz as a valid extension) or if we should fix in element-android going forward and accept currently deployed apps'  log submissions will be made into generic logs-0000.txt.gz files.

**Comment by michaelkaye** [comment]
This is also true of element-web, which submits logs (i believe) with a name similar to `instance-123152` - however it's less of a problem there as all logs are of the same type; and it submits them in reverse chronological order, so it's easier to manage.

**Comment by michaelkaye** [comment]
This is now deployed on the matrix.org server, logs are now named correctly when uploaded.

**Comment by bmarty** [comment]
Thanks a lot for this fix @michaelkaye ! I was wondering since a long time why we had this diff in the files name.
I confirm that we now have better filenames on the rageshakes:
<img width="140" alt="image" src="https://user-images.githubusercontent.com/3940906/151204464-9584144a-058e-40d9-83f1-8db763edeee8.png">
