### ISSUE TITLE
Rageshake should support defining a retention period

### ISSUE THREAD

**Issue by benbz** [matrix-org/rageshake#59]
**Is your feature request related to a problem? Please describe.**
For the purpose of not holding onto data longer than needed (are Rageshakes older than 1 year still going to contain useful and actionable information?) and for storage management reasons, Rageshake should cleanup rageshakes older than a configurable period of time

**Describe the solution you'd like**
A configuration option in Rageshake defining a retention period and Rageshake having a process to safely remove rageshakes outside of this retention period

**Describe alternatives you've considered**
A cronjob that does this outside of Rageshake. Without knowing more about Rageshake's internals I can't say whether or not this is safe. Regardless all deployments of Rageshake could benefit from the retention period so doing it in Rageshake gives it to all deployments with minimal extra work

**Additional context**
n/a

**Comment by michaelkaye** [comment]
Additionally, we probably want to search for all items that have certain properties recorded in their details.log.gz, for example the application or the version of the code - i can imagine that unreleased code rageshakes have a lower value over time compared to released code - this is probably a infrequent cross-item search use-case that  `grep` on a filesystem would be great for  (vs the object storage in #60).

(and yes, we could additionally implement a database to store the contents of the details.log.gz and be able to search that for objects to remove instead)

**Comment by michaelkaye** [comment]
So while rageshakes itself doesn't provide a retention period; the provided script can easily run as a cronjob to clean up behind the rageshakes server (as we only write in day-by-day folders).
