### ISSUE TITLE
Unclear "internal server error 500" when reporting bugs

### ISSUE THREAD

**Issue by cbrhaze** [matrix-org/rageshake#63]
Hello! I have a question that I'm not able to investigate furthre without help.
I have rageshake running. It's config includes only e-mailing + listing access details. No other integrations, so I suppose ragehake should e-mail me + keep data in it's own DB. Logs are available by Web at api/listing with the creds specified.

But there are a couple of problems:
1. E-mails don't arrive, if they should, SMTP settings should be all good
2. User report logs are available on the rageshake server, but:

- the app user gets (500 internal server error when reporting). It's important to mention that as I need HTTPS not HTTP connection to Rageshare, I deployed a TLS-terminating reverse proxy in front of rageshake, so it's the same port, but HTTPS. Maybe it may be related.
- I can't undestand where can I find screenshots if the app user chose to attach them

And the biggest pain is that I'm absolutely not getting how can I check rageshake logs (errors). It's being sent only to the console when running _build rageshake_ so I nothing else can be found as a log file for the service itself?

Here is my config. I'd appreciate your help with any of questions above:

```
listings_auth_user: shake
listings_auth_pass: examplepass

email_addresses:
  - some@adr

# this is the from field that will be used in the email notifications
email_from: Rageshake <rageshake@example.domain>

# SMTP server configuration
smtp_server: mail.some.server:25
smtp_username: rageshake@example.domain
smtp_password: somepass
```

**Comment by richvdh** [comment]
> And the biggest pain is that I'm absolutely not getting how can I check rageshake logs (errors). It's being sent only to the console when running `build rageshake` so I nothing else can be found as a log file for the service itself?

Assuming by `build rageshake` you mean  `go build`, note that that doesn't start the rageshake server; to do that you need to run `./rageshake` after building it. When you do so, the logs will be written to the console (directing them elsewhere is up to you).

Once you have the logs, you can diagnose the other errors.

I'm going to close this as it doesn't seem like a coherent bug report, but we can reopen if you can be more explicit about your problem.
