### ISSUE TITLE
Migrate off BuildKite

### ISSUE THREAD

**Issue by benbz** [matrix-org/rageshake#66]
We're ramping down our BuildKite usage and this project is one of the few left on it. How much work would it be to migrate to GH Actions/similar so that CI was under your span of control?

**Comment by clokep** [comment]
Seems to be #64.

**Comment by benbz** [comment]
Woo, thanks for pointing that out. Michael is ahead of the game here :)

**Comment by michaelkaye** [comment]
(re-opening as we need to tidy up the BK side too)

**Comment by benbz** [comment]
All archived in BK and in the pipelines repo
