### ISSUE TITLE
Second line in produced log file produce non-printable characters

### ISSUE THREAD

**Issue by Porkepix** [matrix-org/rageshake#83]
The first two lines of the log `log-0.log` file are as below:

```
2023-11-27T11:17:07.203Z D Initialised rageshake.
2023-11-27T11:17:07.206Z D To fix line numbers in Chrome: Meatball menu <92> Settings <92> Ignore list <92> Add /rageshake\.ts & /logger\.ts$
```

We can see all these <92> which are not printed. I tried to look for texts fragments in the repo to find where does this come from but wasn't able to find it. It looks like it should be `\`, but might be something else depending on the encoding.

**Comment by richvdh** [comment]
I'm not seeing this; the second line of our rageshakes are:

```
2024-03-04T10:30:23.481Z D To fix line numbers in Chrome: Meatball menu → Settings → Ignore list → Add /rageshake\.ts & /logger\.ts$
```

The `→` characters are "rightwards arrow", with unicode codepoint U+2192 (and UTF-8 encoding `e2 86 92`), so I guess *something* is misinterpreting the unicode. But I have no idea what -- everything should be safely encoded as UTF-8.

How exactly are you accessing the log file? Via the HTTP API, or via direct access to the file system? And what are you using to look at the file?

**Comment by richvdh** [comment]
Ok, without clear reproduction steps I don't think there's much we can do here.

If you can reproduce it, I'd suggest inspecting the file that actually ends up on the filesystem with something like `hexdump -C` to check whether that has the same problem.

If you get more details, let us know and we can reopen.
